openapi: 3.0.0
info:
  title: User Management API
  version: 1.0.0
  description: API for user management operations by Himjyoti Talukdar
servers:
  - url: http://localhost:5000  # Replace with your actual server URL
securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    name: JWT  # Optional, can be omitted
security:
  - bearerAuth: []  # Apply Bearer token authentication globally (optional)
paths: {}  # Placeholder for API endpoint definitions (replace with actual paths and operations)
components:  # Optional section for reusable components
  securitySchemes:  # Redundant with top-level securitySchemes (remove if not used elsewhere)
    bearerAuth:
      type: http
      scheme: bearer
      name: JWT  # Optional, can be omitted
  responses: {}  # Optional section for defining reusable response objects

# Import user controller functions here (replace with actual import statement)
# { getUserProfile, editUserProfile, getAllPublicProfiles, getAllProfiles } = require('../controllers/userController')

# Define security requirements for each endpoint (optional)
# security:
#   getUserProfile:
#     - bearerAuth: []
#   editUserProfile:
#     - bearerAuth: []
#   getAllPublicProfiles: []  # Public endpoint, no security required
#   getAllProfiles:
#     - bearerAuth: []  # Admin-only endpoint

# Loop through user controller functions and add corresponding API paths and operations here
